// <auto-generated />
namespace DataModel.Data.TransactionalLayer.MigrationsSql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class StoreCreditTransactionChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreCreditTransactionChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201507242148559_StoreCreditTransactionChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
