// <auto-generated />
namespace DataModel.Data.TransactionalLayer.MigrationsMySql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddedNdFeeToConsignorPmt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedNdFeeToConsignorPmt));
        
        string IMigrationMetadata.Id
        {
            get { return "201503312258170_AddedNdFeeToConsignorPmt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
